### ISSUE TITLE
Missing artifact com.github.ralfstuckert.pdfbox-layout:pdfbox2-layout:jar:1.0.0

### ISSUE THREAD

**Issue by SaicharanKolaAutomation** [naveenanimation20/LatestCucumber6WithPOM#6]
Hey Naveen,

![image](https://user-images.githubusercontent.com/85512361/121500884-54685f80-c9fc-11eb-95b5-37ab18d15f5b.png)

Getting this issue when I import the project on my local, Can you help on this.

Below is the error code:
Missing artifact com.github.ralfstuckert.pdfbox-layout:pdfbox2-layout:jar:1.0.0

Thanks in Advance!
Much appreciated :)

**Comment by cngramesh** [comment]
I got the same problem, After adding the following to the POM.xml file solved the issue. 


</properties>
	<repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
   
	<dependencies>
 <dependency>
        <groupId>com.github.ralfstuckert.pdfbox-layout</groupId>
        <artifactId>pdfbox2-layout</artifactId>
        <version>1.0.1</version>
    </dependency>

**Comment by kavitha-harish** [comment]
![image](https://user-images.githubusercontent.com/81792515/122875276-aa6cc980-d351-11eb-9802-479c1b4f6b23.png)
i am also facing same error

**Comment by puneethnath86** [comment]
Yes, it worked for me as well after adding the above repository within <repositories> tag and dependency. 
If adding the above 2 also doesn't work then please try to add the below repository as well

<repositories>
	<repository>
		<id>mulesoft-releases</id>
		<name>MuleSoft Repository</name>
		<url>https://repository.mulesoft.org/nexus/content/repositories/public/</url>
	</repository>

This is the link for the solution that I found
https://github.com/jitpack/jitpack.io/issues/4490

Hope it helps, happy coding

**Comment by kavitha-harish** [comment]
Hello,

Extent pdf report is not working for me

It is showing error

**Comment by nguyenthuongquan** [comment]
Upgrade dependency **extentreports-cucumber6-adapter** to version **2.8.2** solved the problem for me

**Comment by grasshopper7** [comment]
All the dependency import and repository settings are no longer required in latest version 2.8.2 and in future releases.

**Comment by manishbupadhyay** [comment]
I was getting same error message but after adding below lines in pom.xml issue get resolve.

<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>

<dependency>
        <groupId>com.github.ralfstuckert.pdfbox-layout</groupId>
        <artifactId>pdfbox2-layout</artifactId>
        <version>1.0.1</version>
    </dependency>

![image](https://user-images.githubusercontent.com/11785569/139816967-7a66a857-a605-433e-a675-8a15b384c391.png)

**Comment by anima-bh** [comment]
> **extentreports-cucumber6-adapter**

this worked for me as well.

**Comment by antonydass** [comment]
Wow.. Super.. this solution worked for me too. Thank you so much

**Comment by Vinu17** [comment]
It really helps, Thank you everyone . By any chance anyone of you would be able to explain the reason why it was not happening  and what made it solved.

**Comment by ksauravjha** [comment]
<dependency>
			<groupId>tech.grasshopper</groupId>
			<artifactId>extentreports-cucumber6-adapter</artifactId>
			<version>2.8.2</version>
			<scope>test</scope>
	  </dependency>

Adding above one has resolved the issue.

**Comment by gopinathking** [comment]
thanq @ksauravjha

**Comment by mamin102** [comment]
still my extent report is not working neither PDF report
